[package]
name = "markdown-html"
version = "1.0.0"
authors = ["gauravsaini"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
pulldown-cmark = "0.7.1"
maud = "0.21.0"
